### ISSUE TITLE
Wildcard purging

### ISSUE THREAD

**Issue by tollmanz** [CondeNast/purgely#12]
I just read about the [Wildcard purging](https://docs.fastly.com/guides/purging/wildcard-purges) today. I'm still trying to fully grok it. It looks like the WP plugin can handle the first two items related to setting surrogate keys. I'm not sure about the [Create conditions for each wildcard path being purged](https://docs.fastly.com/guides/purging/wildcard-purges#create-conditions-for-each-wildcard-path-being-purged).

@simonwistow What are your thoughts on this? On the one hand, this seems really cool; on the other, it just seems like a use case for surrogate key purging. Let me know what you think.

**Comment by simonwistow** [comment]
I think it's just a use case for Surrogate-Key - not entirely sure it's useful here ... it's mostly used for purging directories or multiple files in the different directories

**Comment by tollmanz** [comment]
Closing this as it just doesn't seem relevant.
