### ISSUE TITLE
Possible key values

### ISSUE THREAD

**Issue by tollmanz** [CondeNast/purgely#19]
Do the Fastly Service ID and API Key strings only contain the following characters: `a-zA-B0-9`? I'm currently restricting the values to those characters and want to make sure I don't break anything.

Ping @simonwistow

**Comment by simonwistow** [comment]
The service id is a base62 encoded [UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier) so, yeah, you're right, it's `a-zA-Z0-9`.

The API key is just hex so `a-fA-F0-9` if you want to be really strict but it's probably best to just check the same `a-zA-Z0-9`.

**Comment by tollmanz** [comment]
Thanks!
