### ISSUE TITLE
API endpoint

### ISSUE THREAD

**Issue by tollmanz** [CondeNast/purgely#22]
Do we need to have a config value for setting the API endpoint? I think I added this initially because the original Fastly plugin allowed this to be configured. Is there any case where the API endpoint would be anything other than `https://api.fastly.com/`? I guess I could see Fastly moving to something like `https://v2.api.fastly.com/` or `https://api.fastly.com/v2` if they updated the API. In that case, the plugin would just be updated.

Do we need this option @simonwistow?

**Comment by simonwistow** [comment]
Looks like you've already provided it. We're not planning on changing our API endpoint anytime soon though.
