### ISSUE TITLE
Publishing a new post doesn't purge the URL of the published post.

### ISSUE THREAD

**Issue by lukebussey** [CondeNast/purgely#31]
We just switched over to Purgely because the Fastly plugin stopped working for us at Yesware. I really like the surrogate-key approach to purging, especially for updating posts which we do often.

We're now running into an issue with publishing new posts where we inadvertently prime the cache with a 404 by testing links internally before we publish.Obviously then when publishing a post, it doesn't go live, because Purgely isn't clearing the URL of the page being published.

Any thoughts? Is it simple to fix, or could you point me in the right direction to fix this?

**Comment by tollmanz** [comment]
Closing as we mostly discussed this over here: https://github.com/CondeNast/purgely/pull/30.
