### ISSUE TITLE
Soft purge as the default?

### ISSUE THREAD

**Issue by tollmanz** [CondeNast/purgely#9]
Would it make sense to have soft purge be the default? This just seems like a wise default. Yes, it means no instant purge, but it probably the safest bet for a plugin that aims to work across different WordPress setups.

**Comment by simonwistow** [comment]
Yeah, seems sensible. I can't think of any reason not to do it off the top of my head.

**Comment by tollmanz** [comment]
Thanks @simonwistow! The more I work on the WIRED integration, I keep using soft purges. Since we are defaulting to 24 hour `stale-while-revalidate` and `stale-while-error`, I think soft purging as a default makes sense.

I'll change the default behavior to use soft purging and add a config option to override it.

**Comment by tollmanz** [comment]
#11 opened to implement this feature.
